## [APP]
spring:
  application:
    name: hsd-eureka-server
  profiles:
    active: dev

server:
  port: 5001


## [EUREKA]
eureka:
  server:
    enable-self-preservation: true       # 关闭自我保护模式（缺省为打开）
    eviction-interval-timer-in-ms: 1000   # 续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）
    waitTimeInMsWhenSyncEmpty: 0.1
  instance:
#    instance-id: ${spring.application.name}:${server.port}
    hostname: hsd-eureka-server
    prefer-ip-address: true                       # 设置微服务调用地址为IP优先（缺省为false）
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-renewal-interval-in-seconds: 5          # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 15      # 发呆时间，即服务续约到期时间（缺省为90s）
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@localhost:${server.port}/eureka/

## [SECURITY]
security:
     basic:
       enabled: false
     user:
       name: admin
       password: admin

## [MANAGEMENT]
management:
  security:
    enabled: false

## [LOG]
logging:
  level.root: debug
  path: ./logs/hsd-eureka-server   # not working this moment, since logback-spring will be first used by

## [INFO]
info:
  name: "@project.name@"
  description: "@project.description@"
  version: "@project.version@"
  spring-boot-version: "@project.parent.version@"

## [OTHER]
hsd:
  common:
    appPrefix: dev_   #指定app前缀（开发中可使用IP），系统在队列名、Cache名等前会自动加上前缀，以便不同环境冲突


