## [APP]
spring:
  application:
    name: hsd-gitlab-hooks-server
  profiles:
    active: dev
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
  datasource:
      url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      filters: log4j,wall,mergeStat

server:
  port: 5100


## [MYBATIES-PLUS]
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.hsd.gitlab.systemhook.domain
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用


## [ZUUL]
zuul:
  sensitiveHeaders: Access-Control-Allow-Origin,Access-Control-Allow-Methods,Access-Control-Allow-Headers
  cross:
    origin: "*"
    methods: "POST, GET, OPTIONS, PUT, DELETE, HEAD"
    headers: "Origin,Authorization,Cache-Control,Content-Language,Content-Type,Expires,Last-Modified,Pragma,X-Cache"
  max:
    host:
      connections: 500
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
#  ignored-services: "*"
#  routes:
#    product:
#      path: /product/**
#      url: http://product:9001/product

## [HYSTRIX]
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
  stream:
    maxConcurrentConnections: 20
    bus:
      enabled: true


## [RIBBON]
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  eureka:
    enabled: true
  okhttp:
      enabled: true


## [ENDPOINTS]
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
  cors:
    allowed-methods: HEAD,GET,POST


## [MANAGEMENT]
management:
  security:
    enabled: false

## [LOG]
logging:
  level.root: debug
  path: ./logs/hsd-gitlab-hooks-server   # not working this moment, since logback-spring will be first used by

## [INFO]
info:
  name: "@project.name@"
  description: "@project.description@"
  version: "@project.version@"
  spring-boot-version: "@project.parent.version@"

## [OTHER]
feign:
  client:
    name: hsd-gitlab-hooks-server
  okhttp:
    enabled: true
  hystrix:
    enabled: true

hsd:
  common:
    appPrefix: dev_   #指定app前缀（开发中可使用IP），系统在队列名、Cache名等前会自动加上前缀，以便不同环境冲突

swagger:
  swagger-open: true


  


